# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 08:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('desc', models.TextField(default='No Description')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('photo_types', models.CharField(choices=[('People', 'people'), ('Nature', 'nature'), ('Black & White', 'black & white')], default='People', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.CharField(default='No Title', max_length=100)),
                ('content', models.TextField(default='No Content')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('post_types', models.CharField(choices=[('Published', 'published'), ('Stories', 'stories'), ('Travelogue', 'travelogue')], default='Published', max_length=20)),
            ],
        ),
    ]
