# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='title',
            field=models.CharField(default='No Title', max_length=20),
        ),
    ]
