# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_auto_20160407_0224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_types',
            field=models.CharField(choices=[('People', 'people'), ('Nature', 'nature'), ('Black & White', 'black & white')], default='people', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_types',
            field=models.CharField(choices=[('Published', 'published'), ('Stories', 'stories'), ('Travelogue', 'travelogue')], default='published', max_length=20),
        ),
    ]
