# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 17:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_auto_20160407_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo_types',
            field=models.CharField(choices=[('people', 'People'), ('nature', 'Nature'), ('bnw', 'Black & White')], default='people', max_length=20),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_types',
            field=models.CharField(choices=[('published', 'Published'), ('stories', 'Stories'), ('travelogue', 'Travelogue')], default='published', max_length=20),
        ),
    ]
