# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-07 17:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_auto_20160407_2313'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='photo_types',
            new_name='photo_type',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='post_types',
            new_name='post_type',
        ),
    ]
