# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_auto_20160407_2326'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='desc',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='title',
        ),
    ]
