# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_auto_20160409_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='file',
            field=models.ImageField(upload_to='uploads/'),
        ),
    ]
