# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_auto_20160410_0134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='conten',
            new_name='content',
        ),
    ]
