# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 20:33
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_auto_20160410_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 4, 9, 20, 33, 16, 918313, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
