# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0012_comment_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='email',
            field=models.CharField(default='anonymous', max_length=30),
        ),
    ]
