# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-15 19:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_subcribers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='subcribers',
            new_name='subscribers',
        ),
    ]
