# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_auto_20160416_0100'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment_photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Anonymous', max_length=20)),
                ('email', models.CharField(default='anonymous', max_length=30)),
                ('content', models.TextField(default='no-content')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.photo')),
            ],
        ),
    ]
