# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-04-16 20:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0016_comment_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment_photo',
            old_name='post',
            new_name='photo',
        ),
    ]
