# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-01 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_auto_20160417_0143'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file',
            field=models.ImageField(default='settings.MEDIA_ROOT/posts/blank.jpg', upload_to='posts/'),
        ),
    ]
