# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-21 18:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0020_auto_20160617_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_type',
            field=models.CharField(choices=[('published', 'Published'), ('untold', 'Untold'), ('travelogue', 'Travelogue')], default='published', max_length=20),
        ),
    ]
